# Generated by Django 6.1 on 2026-09-17 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('fleet', '0003_alter_vehicle_options'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='payload_capacity_kg',
            new_name='capacity_kg',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='odometer',
            new_name='odometer_km',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vin_number',
            new_name='vin',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ad_blue_level_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_oil_life_percent',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_level_percent',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='temperature_sensor',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('bus', 'Bus'), ('mini_truck', 'Mini Truck'), ('heavy_truck', 'Heavy Truck'), ('reefer_cold', 'Reefer / Cold Storage'), ('flatbed', 'Flatbed'), ('container', 'Container')], db_index=True, default='heavy_truck', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vertical',
            field=models.CharField(choices=[('taxi_cab', 'Taxi / Cab'), ('tourist_bus', 'Tourist Bus'), ('freight_logistics', 'Freight Logistics'), ('packers_movers', 'Packers & Movers'), ('b2b_contract', 'B2B Contract'), ('cold_chain', 'Cold Chain'), ('last_mile', 'Last Mile'), ('heavy_machinery', 'Heavy Machinery'), ('courier_express', 'Courier Express'), ('corporate_shuttle', 'Corporate Shuttle'), ('all_verticals', 'All Verticals')], db_index=True, default='freight_logistics', max_length=50),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.branch'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant', 'vertical'], name='fleet_vehic_tenant__a99c51_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant', 'type'], name='fleet_vehic_tenant__9caea0_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'name'], name='fleet_branc_tenant__68067a_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'is_active'], name='fleet_branc_tenant__eb7b15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('tenant', 'code')},
        ),
    ]
